# Generated by Django 4.1.3 on 2023-04-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='distrito',
            field=models.CharField(default=' ', max_length=250),
            preserve_default=False,
        ),
    ]
