# Generated by Django 4.1.3 on 2023-04-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='NSID',
            field=models.CharField(default=' ', max_length=250),
        ),
        migrations.AddField(
            model_name='profile',
            name='cidade',
            field=models.CharField(default=' ', max_length=250),
        ),
        migrations.AddField(
            model_name='profile',
            name='pnome',
            field=models.CharField(default=' ', max_length=250),
        ),
        migrations.AddField(
            model_name='profile',
            name='snome',
            field=models.CharField(default=' ', max_length=250),
        ),
    ]
